cake-contrib/Cake.AzureDevOps

setup.cake
src/Cake.Tfs.Tests/ArgumentChecksTests.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestSettingsTests.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs
src/Cake.Tfs/ArgumentChecks.cs
src/Cake.Tfs/Cake.Tfs.csproj
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestSettings.cs
src/Cake.Tfs/PullRequest/TfsPullRequestVote.cs
src/Cake.Tfs/TfsAliases.Authentication.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs
src/Cake.Tfs/TfsAliases.cs

Add alias for voting on pull request
Fixes #3

(GH-3) Alias for voting on pull request

---

src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Add alias for retrieving commit ID of pull request
Fixes #4

(GH-4) Add alias for retrieving commit ID of pull request

---

src/Cake.Tfs.Tests/PullRequest/TfsPullRequestSettingsTests.cs
src/Cake.Tfs/PullRequest/TfsPullRequestSettings.cs

Add overload for creating a setting class from an existing instance
Fixes #24

(GH-24) Add overload for creating a setting class from an existing instance

---

src/Cake.Tfs/PullRequest/TfsPullRequest.cs

Provide commit Id of pull request target branch
Fixes #27

(GH-27) Provide commit Id of pull request target branch

---

README.md
docs/input/index.cshtml
nuspec/nuget/Cake.Tfs.nuspec
src/Cake.Tfs/Authentication/AuthenticationProvider.cs
src/Cake.Tfs/Cake.Tfs.csproj
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestSettings.cs
src/Cake.Tfs/PullRequest/TfsPullRequestVote.cs
src/Cake.Tfs/TfsAliases.Authentication.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs
src/Cake.Tfs/TfsAliases.cs
src/Cake.Tfs/TfsException.cs

Rename VSTS to Azure DevOps

---

src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestStatus.cs
src/Cake.Tfs/PullRequest/TfsPullRequestStatusState.cs
src/Cake.Tfs/PullRequest/TfsPullRequestStatusStateExtensions.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Add alias to set status on pull request
Fixes #30

(GH-30) Add alias to set status on pull request

---

src/Cake.Tfs.Tests/ExceptionAssertExtensions.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestSettingsTests.cs
src/Cake.Tfs/PullRequest/TfsPullRequestSettings.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Implement the settings object construction from the predefined TFS/Azure DevOps environment variables.
Fixes #29

(GH-29) Implement the settings object construction from env vars

---

src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestNotFoundException.cs

Throw specific exception in case pull request could not be found
Fixes #37

(GH-37) Throw specific exception in case pull request could not be found

---

src/Cake.Tfs.Tests/Cake.Tfs.Tests.csproj

Update XUnit to 2.4.1

---

azure-pipelines.yml

Add build definition for Azure Pipelines

Add build definition for Azure Pipelines

---

src/Cake.Tfs/Cake.Tfs.csproj

Update TfsUrlParser to 1.3.0-beta1
Fixes #56

(GH-56) Update TfsUrlParser to 1.3.0-beta1

---

src/Cake.Tfs.Tests/ExceptionAssertExtensions.cs
src/Cake.Tfs.Tests/PullRequest/BasePullRequestFixture.cs
src/Cake.Tfs.Tests/PullRequest/CreatePullRequestFixture.cs
src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.Tfs.Tests/PullRequest/PullRequestFixture.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestSettingsTests.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs
src/Cake.Tfs/PullRequest/BaseTfsPullRequestSettings.cs
src/Cake.Tfs/PullRequest/TfsBranchNotFoundException.cs
src/Cake.Tfs/PullRequest/TfsCreatePullRequestSettings.cs
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestSettings.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Add functionality to create pull requests.
Fixes #15

(GH-15) Add pull request creation functionality

---

src/Cake.Tfs/TfsAliases.Authentication.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Import namespaces on method level
Fixes #86

(GH-86) Import namespaces on method level

---

src/Cake.Tfs.Tests/Cake.Tfs.Tests.csproj
src/Cake.Tfs/Cake.Tfs.csproj

Build against Cake 0.33
Fixes #90

(GH-90) Build against Cake 0.33

---

src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.Tfs.Tests/PullRequest/PullRequestStatusExtensionsTests.cs
src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs
src/Cake.Tfs/PullRequest/PullRequestStatusExtensions.cs
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/PullRequest/TfsPullRequestState.cs

Return pull request status
Fixes #89

(GH-89) Return pull request status

---

src/Cake.Tfs/PullRequest/TfsPullRequest.cs

Improve error handling while creating pull requests
Fixes #111

(GH-111) Improve error handling while creating pull requests

---

src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.Tfs/Cake.Tfs.csproj

Update Azure DevOps assemblies to 16.143.2
Fixes #115

(GH-115) Update Azure DevOps assemblies to 16.143.2

---

azure-pipelines.yml
build.sh
setup.cake

Build and test pull requests on Linux
Fixes #128

Build / Test on Linux

---

README.md

Add Ubuntu build to README

---

src/Cake.Tfs/PullRequest/GitClient/IGitClientFactory.cs
src/Cake.Tfs/PullRequest/TfsPullRequest.cs
src/Cake.Tfs/TfsAliases.PullRequest.cs

Make `IGitClientFactory` internal
Fixes #122

(GH-122) Make IGitClientFactory internal

---

src/Cake.Tfs.Tests/PullRequest/CommentThread/TfsCommentTests.cs
src/Cake.Tfs.Tests/PullRequest/CommentThread/TfsPullRequestCommentThreadTests.cs
src/Cake.Tfs/PullRequest/CommentThread/TfsComment.cs

Remove constructor which accepts internal comment type
Fixes #124

(GH-124) Remove constructor which accepts internal comment type

---

README.md

(GH-126) Add link to demo

---

README.md

Fix links of Demo badges

---

src/Cake.AzureDevOps.Tests/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs
src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequest.cs

Adds an alias for adding comment to pull request
Fixes #161

(GH-161) Add alias for adding comment to pull request

---

src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs

Fix indentation for examples
Fixes #165

(GH-165) Fix indentation for examples

---

src/Cake.AzureDevOps/Build/AzureDevOpsBuild.cs

Return parameters / variables of build 
Fixes #171

(GH-171) Return parameters of build 

---

src/Cake.AzureDevOps/Build/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Build/AzureDevOpsBuildStatus.cs
src/Cake.AzureDevOps/Build/BuildStatusExtensions.cs

Return status of builds.
Fixes #174

(GH-174) Return build status

---

src/Cake.AzureDevOps/Build/BuildClient/BuildClientFactory.cs

Fix name of variable

---

src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs
src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequest.cs
src/Cake.AzureDevOps/Repos/AzureDevOpsCommit.cs
src/Cake.AzureDevOps/Repos/GitCommitRefExtensions.cs

Return commits of a pull request
Fixes #178

(GH-178) Return commits of a pull request

---

src/Cake.AzureDevOps/PullRequest/AzureDevOpsCreatePullRequestSettings.cs

Add method to create AzureDevOpsCreatePullRequestSettings using Azure Pipelines OAuth token

(GH-179) Add method to create AzureDevOpsCreatePullRequestSettings from OAuth token

---

src/Cake.AzureDevOps.Tests/Properties/AssemblyInfo.cs
src/Cake.AzureDevOps.Tests/PullRequest/AzureDevOpsPullRequestSettingsTests.cs

Fix flaky tests by disabling running them in parallel

Fix flaky tests

---

src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs
src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequestSettings.cs

Add AzureDevOpsPullRequestUsingAzurePipelinesOAuthToken overload which does not throw an exception
Fixes #185

(GH-185) Add AzureDevOpsPullRequestUsingAzurePipelinesOAuthToken overload which does not throw

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildResult.cs
src/Cake.AzureDevOps/Pipelines/BuildResultExtensions.cs

Return result of a build.
Fixes #173

(GH-173) Return build result

---

src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs

Fix null reference exception while not running under Azure Pipelines.
Fixes #193

(GH-193) Fix null reference exception

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequest.cs

Use best practices for async calls

Improve async calls

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsTaskResult.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsTimelineRecord.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsTimelineRecordState.cs
src/Cake.AzureDevOps/Pipelines/TaskResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/TimelineRecordExtensions.cs
src/Cake.AzureDevOps/Pipelines/TimelineRecordStateExtensions.cs

Add method to return build timeline records
Fixes #198

(GH-198) Add method to return build timeline records

---

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs

Add aliases for newly introduced methods

Add aliases for newly introduced methods

---

src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs

Add alias for returning commits of a pull request
Fixes #206

(GH-206) Add alias for returning commits of a pull request

---

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

Add method to check if a running build is failing 
Fixes #199

(GH-199) Add method to check if build is failing 

---

src/Cake.AzureDevOps/Pipelines/ArtifactResourceExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsArtifactResource.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildArtifact.cs
src/Cake.AzureDevOps/Pipelines/BuildArtifactExtensions.cs

(GH-176) Return artifacts of a build

---

src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsSettingsTests.cs
src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
src/Cake.AzureDevOps/EnvironmentVariableHelper.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildQueryOrder.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildQueryOrderExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsHelper.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsSettings.cs
src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequestSettings.cs

(GH-234) Add an alias to get builds by specific settings

---

src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildsSettingsTests.cs

Fix naming of test class and test methods

Fix naming of test class and test methods

---

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsTestResult.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsTestRun.cs
src/Cake.AzureDevOps/Pipelines/TestManagementClient/ITestManagementClientFactory.cs
src/Cake.AzureDevOps/Pipelines/TestManagementClient/TestManagementClientFactory.cs

Add test runs and test results to build. Resolves #243

(GH-243) Add test runs and test results to build

---

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs

Add alias for GetArtifacts method on AzureDevOpsBuild class. Resolves #245

(GH-245) Add alias for GetArtifacts method on AzureDevOpsBuild class

---

src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCollectionSettingsImpl.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCollectionSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCredentialsSettingsImpl.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCredentialsSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsProjectSettingsImpl.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsProjectSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildsSettingsTests.cs
src/Cake.AzureDevOps/BaseAzureDevOpsCollectionSettings.cs
src/Cake.AzureDevOps/BaseAzureDevOpsCredentialsSettings.cs
src/Cake.AzureDevOps/BaseAzureDevOpsProjectSettings.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildSettings.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsSettings.cs
src/Cake.AzureDevOps/Repos/PullRequest/BaseAzureDevOpsPullRequestSettings.cs

Introduces classes for common settings.
Fixes #236

(GH-236) Introduce common base settings class

---

src/Cake.AzureDevOps/BuildClientFactory.cs
src/Cake.AzureDevOps/GitClientFactory.cs
src/Cake.AzureDevOps/IBuildClientFactory.cs
src/Cake.AzureDevOps/IGitClientFactory.cs
src/Cake.AzureDevOps/ITestManagementClientFactory.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/TestManagementClientFactory.cs

Unify client factory interfaces

Unify client factory interfaces

---

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

Allow to pass test management client factory

Allow to pass test management client factory

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

Add methods to add artifact link to build
Fixes #272

(GH-272) Add methods to add artifact link to build

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

Return all test results for a test run

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

GH-261) Add FinishTime property to AzureDevOpsBuild

---

src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullForMethodsGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/BasePullRequestFixture.cs
src/Cake.AzureDevOps/GitClientFactory.cs
src/Cake.AzureDevOps/IGitClientFactory.cs

Cleanup namespaces for Git client

Cleanup namespaces for Git client

---

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

Fix table in comment

---

README.md
docs/input/_Bottom.cshtml

Update README: Add link to GitHub Discussions

---

recipe.cake

Exclude Cake.Testing and Moq from code coverage

Exclude Cake.Testing and Moq from code coverage

---

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj

Migrate from FxCop analyzers to NETAnalyzers

Migrate from FxCop analyzers to NETAnalyzers

---

recipe.cake

Ignore Cake.Common for code coverage

Ignore Cake.Common for code coverage

---

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildDefinition.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsDefinitionHelper.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsHelper.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsDefinitionQueueStatus.cs
src/Cake.AzureDevOps/Pipelines/BuildDefinitionReferenceExtensions.cs
src/Cake.AzureDevOps/Pipelines/DefinitionQueueStatusExtensions.cs

(GH-265) Add an alias to get all build definitions for a project

---

azure-pipelines.yml
build.ps1
src/Cake.AzureDevOps.Tests/Cake.AzureDevOps.Tests.csproj
src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsDefinitionQueueStatus.cs

- Update Cake reference to 2.0
- Update packages
- Increase version to 1.2.0

(GH-325) Update Cake to 2.0

---

src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetTestManagementClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeTestManagementClientFactory.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/BuildFixture.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs

(GH-275) Add option to filter test results in GetTestRuns to specific test outcomes

---

.github/dependabot.yml

Ignore Cake updates until 3.0

---

.appveyor.yml

Update to Visual Studio 2022 image as we need to target .NET 6 and additionally install .NET Core 2.1

Install .NET Core 2.1

---

.appveyor.yml

Provide all .NET versions for AppVeyor

Fix all .NET versions for AppVeyor

---

recipe.cake

Disable Wyam and code coverage until issues on AppVeyor are fixed

Disable Wyam and code coverage until issues on AppVeyor are fixed

---

recipe.cake

Update Coveralls tool

---

src/Cake.AzureDevOps.Tests/ExceptionAssertExtensions.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetTestManagementClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullForMethodsGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildsSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/CommentThread/AzureDevOpsCommentTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThreadTests.cs
src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThread.cs

Fix warnings

---

azure-pipelines.yml

Run macOS tests on macOS 11

---

azure-pipelines.yml

Run Ubuntu tests on Ubuntu 20.04

Run Ubuntu tests on Ubuntu 20.04

---

tests/frosting/net5.0/build/Program.cs
tests/frosting/net6.0/build/Program.cs
tests/frosting/netcoreapp3.1/build/Program.cs
tests/script-runner/net5.0/build.cake
tests/script-runner/net6.0/build.cake
tests/script-runner/netcoreapp3.1/build.cake

Add more integration tests

---

src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs

Provides a new method `CloseCommentThread`.
Fixes #365

(GH-365) Add method to close comment thread

---

src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs

Output correct number of files in log message
Fixes #368

(GH-368) Fix log message

---

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj

Add missing assembly.
fixes #370

Add missing dependency

---

src/Cake.AzureDevOps.Tests/Cake.AzureDevOps.Tests.csproj
src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
tests/frosting/net6.0/build/Build.csproj
tests/frosting/net7.0/build/Build.csproj
tests/script-runner/net6.0/.config/dotnet-tools.json
tests/script-runner/net7.0/.config/dotnet-tools.json

Builds against Cake 3.0
Fixes #377

Build against Cake 3.0

---

src/.editorconfig
src/Cake.AzureDevOps.Tests/Repos/PullRequest/BasePullRequestFixture.cs
src/Cake.AzureDevOps.sln.DotSettings
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildQueryOrderExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/BuildResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/BuildStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/DefinitionQueueStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/TaskResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/TimelineRecordStateExtensions.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestStatusStateExtensions.cs
src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThread.cs
src/Cake.AzureDevOps/Repos/PullRequest/PullRequestStatusExtensions.cs
src/Directory.Build.props

Adds editorconfig file, updates ReSharper settings to match code style and fixes some linting issues

Add editorconfig and fix linting issues

---

src/Cake.AzureDevOps.Tests/ArgumentChecksTests.cs

Fix test case

---

src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps/Pipelines/ArtifactResourceExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildQueryOrderExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/BuildResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/BuildStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/DefinitionQueueStatusExtensions.cs
src/Cake.AzureDevOps/Pipelines/TaskResultExtensions.cs
src/Cake.AzureDevOps/Pipelines/TimelineRecordStateExtensions.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestStatusStateExtensions.cs

Throw specific exceptions instead of `System.Exception`.

Throw specific exceptions

---

src/Cake.AzureDevOps.Tests/ArgumentChecksTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AuthenticationProviderTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AzureDevOpsOAuthCredentialsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCollectionSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCredentialsSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsProjectSettingsTests.cs
src/Cake.AzureDevOps.Tests/Boards/WorkItemTracking/AzureDevOpsWorkItemSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildsSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsCreatePullRequestSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs

Use `const` instead of `var` in test cases

Use const instead of var in test cases

---

azure-pipelines.yml

Fixes build on Windows by making .NET 5 available

Fix build on Windows

---

src/Cake.AzureDevOps.Tests/ArgumentChecksTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AuthenticationProviderTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AzureDevOpsAadCredentialsTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AzureDevOpsBasicCredentialsTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AzureDevOpsNtlmCredentialsTests.cs
src/Cake.AzureDevOps.Tests/Authentication/AzureDevOpsOAuthCredentialsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCollectionSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsCredentialsSettingsTests.cs
src/Cake.AzureDevOps.Tests/BaseAzureDevOpsProjectSettingsTests.cs
src/Cake.AzureDevOps.Tests/Boards/WorkItemTracking/AzureDevOpsWorkItemSettingsTests.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetBuildClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetTestManagementClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetWorkItemTrackingClientFactory.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildSettingsTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildTests.cs
src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildsSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsCreatePullRequestSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestSettingsTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/CommentThread/AzureDevOpsCommentTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThreadTests.cs
src/Cake.AzureDevOps.Tests/Repos/PullRequest/PullRequestStatusExtensionsTests.cs
src/Cake.AzureDevOps.sln.DotSettings
src/Cake.AzureDevOps/ITestManagementClientFactory.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestSettings.cs

Fix linting issues

---

.appveyor.yml

Update required .NET SDK on AppVeyor build

Update .NET SDK on AppVeyor build

---

.github/renovate.json

Change Renovate preset to include Cake.Recipe specific settings

Use Renovate preset for Cake.Recipe based repos

---

src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs

Improve documentation of return values and exceptions of `AzureDevOpsPullRequest`.

Improve exception documentation

---

azure-pipelines.yml

Update macOS versions in build pipeline

Update macOS versions

---

.github/renovate.json

Disables Renovate PRs for Cake .NET Tool and Cake Frosting minor and patch updates

Ignore Cake runner minor and patch updates

---

.config/dotnet-tools.json
recipe.cake

Update to Cake.Recipe 4 Alpha

---

recipe.cake

Enable deterministic builds

---

src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetGitClientFactory.cs
src/Cake.AzureDevOps.Tests/Fakes/FakeNullForMethodsGitClientFactory.cs
src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs

Fix GetModifiedFiles to request all changes
