cake-contrib/Cake.AzureDevOps

src/Cake.Tfs/TfsAliases.PullRequest.cs
Rename `TfsPullRequestVote` alias to `TfsVotePullRequest` to avoid clash with `TfsPullRequestVote` enumeration.
Fixes #22
=> (GH-22) Rename TfsPullRequestVote to TfsVotePullRequest

src/Cake.Tfs.Tests/Cake.Tfs.Tests.csproj, src/Cake.Tfs.Tests/ExceptionAssertExtensions.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeNullForMethodsGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeNullGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/PullRequestFixture.cs, src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs, src/Cake.Tfs/PullRequest/GitClient/GitClientFactory.cs, src/Cake.Tfs/PullRequest/GitClient/IGitClientFactory.cs, src/Cake.Tfs/PullRequest/TfsPullRequest.cs, src/Cake.Tfs/TfsAliases.PullRequest.cs
@pascalberger This is the very first draft to serve as a proof of concept for the idea. It contains just one ugly ctor test using the mocked `GitHttpClient`. I had to make the interface of the factory `public` since it complained when being used from the `public` ctor of the `TfsPullRequest`. 
In general, does it resemble what you have in mind? I would appreciate your review. 
Fixes #14.
=> (GH-14) Add test cases for TFS calls

src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs, src/Cake.Tfs/PullRequest/TfsPullRequest.cs
This brings the `SourceRefName` property and appropriate parts of the unit tests in.
Fixes #36
=> (GH-36) Return source branch for pull request

src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeNullForMethodsGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs, src/Cake.Tfs/Cake.Tfs.csproj, src/Cake.Tfs/PullRequest/TfsPullRequest.cs
This is the start of moving *low-hanging fruits* from Cake.Issues.PullRequests.Tfs in scope of [this one](https://github.com/cake-contrib/Cake.Issues.PullRequests.Tfs/issues/22). I would appreciate your review. 
I had to do a couple of extra things not directly related to the topic:
- Bump the version of TFS client libraries to avoid `Inheritance security rules violated by type` error, which was apparently a [compatibility issue in `System.Net.Http` version 4.1.0](https://stackoverflow.com/questions/45486980/visual-studio-team-services-api-example-throwing-system-net-http-error). Referncing the `System.Net.Http` directly, as suggested in that SO thread, is obviously not an option.
- Introduce a two-param ctor overload for `TfsPullRequest`, as long as it is used in the …
=> (GH-5) Move GetModifiedFiles method from Cake.Issues.PullRequests.Tfs repo

src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeNullForMethodsGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/TfsCommentTests.cs, src/Cake.Tfs.Tests/PullRequest/TfsPullRequestCommentThreadTests.cs, src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs, src/Cake.Tfs/PullRequest/CommentThread/TfsComment.cs, src/Cake.Tfs/PullRequest/CommentThread/TfsCommentThreadStatus.cs, src/Cake.Tfs/PullRequest/CommentThread/TfsCommentType.cs, src/Cake.Tfs/PullRequest/CommentThread/TfsPullRequestCommentThread.cs, src/Cake.Tfs/PullRequest/TfsPullRequest.cs
This is an attempt to continue with [this one](https://github.com/cake-contrib/Cake.Issues.PullRequests.Tfs/issues/22) and move the functionality related to the comment threads. As long as one of the methods was returning `GitPullRequestCommentThread`, I've added some wrapper classes to hide TFS API in `Cake.Tfs`. 
If I understood you correctly, this is one of the alternatives you described. On one hand, it isolates the TFS API, but on the other hand, several classes were introduced for that purpose only... Please, let me know what you think. 
The code lacks some tests and needs polishing. I'll put it into order once we agree on the concept.
I'll also create a separate PR to `Cake.Issues.PullRequests.Tfs` to track how the calling code changes when these enhancements are consumed.
Fixes …
=> Add methods to get and update comment thread and some wrapper classes

src/Cake.Tfs.Tests/ExceptionAssertExtensions.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeAllSetGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/Fakes/FakeNullForMethodsGitClientFactory.cs, src/Cake.Tfs.Tests/PullRequest/TfsPullRequestTests.cs, src/Cake.Tfs/PullRequest/TfsPullRequest.cs, src/Cake.Tfs/PullRequest/TfsPullRequestIterationChange.cs
@pascalberger Hopefully, the last part to support [this one](https://github.com/cake-contrib/Cake.Issues.PullRequests.Tfs/issues/22). The methods to work with pull request iterations and iteration changes were added: `GetLatestIterationId` and `GetIterationChanges`. This enables the removal of the last direct calls to `GitClient` in Cake.Issues.PullRequests.Tfs.
One question though: can we make the `ValidatePullRequest` method of the `TfsPullRequest` public? If so, we won't need a special method in `ITfsPullRequestSystem` interface.
=>  Add methods to work with pull request iterations and iteration changes

src/Cake.Tfs.Tests/PullRequest/CommentThread/TfsPullRequestCommentThreadTests.cs, src/Cake.Tfs/PullRequest/CommentThread/TfsPullRequestCommentThread.cs
Returns default value while reading a property from a comment thread in case property collection is not initialized. Like this the behavior is consistent if the property collection is not initialized or if the property does not exist.
Fixes #84
=> (GH-84) Return default value in case property collection is not initialized

src/Cake.Tfs/TfsAliases.PullRequest.cs
Import `Cake.Tfs.PullRequest.CommentThread` namespace for pull request aliases.
Fixes #82
=>  (GH-82) Import Cake.Tfs.PullRequest.CommentThread namespace 

src/Cake.Tfs/PullRequest/TfsBranchNotFoundException.cs
Fixes parameter for `TfsBranchNotFoundException` constructors.
Fixes #113
=> (GH-113) Fix constructor parameter name

src/Cake.Tfs/3rdPartyLicense.txt, src/Cake.Tfs/Cake.Tfs.csproj
Only pack assemblies required by current functionality into the NuGet package
Fixes #141
=> (GH-141) Only deliver required assemblies

src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequest.cs
Adds a property to `AzureDevOpsPullRequest` to indicate if the pull request is in draft mode
Fixes #156
=> (GH-156) Return if the pull request is in draft mode

src/Cake.AzureDevOps.Tests/PullRequest/AzureDevOpsPullRequestTests.cs, src/Cake.AzureDevOps/PullRequest/AzureDevOpsPullRequest.cs
Throw ArgumentNullException instead of NullReferenceException
Fixes #163
=> (GH-163) Throw ArgumentNullException instead of NullReferenceException

src/Cake.AzureDevOps.Tests/Build/AzureDevOpsBuildSettingsTests.cs, src/Cake.AzureDevOps/AzureDevOpsAliases.Build.cs, src/Cake.AzureDevOps/Build/AzureDevOpsBuild.cs, src/Cake.AzureDevOps/Build/AzureDevOpsBuildNotFoundException.cs, src/Cake.AzureDevOps/Build/AzureDevOpsBuildSettings.cs, src/Cake.AzureDevOps/Build/BuildClient/BuildClientFactory.cs, src/Cake.AzureDevOps/Build/BuildClient/IBuildClientFactory.cs, src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
Add alias for accessing Azure Pipeline information
Fixes #169
=> (GH-169) Add alias for accessing Azure Pipeline builds

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
Add missing `Microsoft.TeamFoundation.DistributedTask.Common.Contracts.dll` to NuGet package.
Fixes #191
=> (GH-191) Fix NuGet packaging

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
Fix description of example for `AzureDevOpsBuild` alias
=> Fix description in example

src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildSettingsTests.cs, src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs, src/Cake.AzureDevOps/EnvironmentVariableHelper.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildSettings.cs
Add overload for `AzureDevOpsBuildSettings.UsingAzurePipelinesOAuthToken` providing a build id 
Resolves #239
=> Add overload for UsingAzurePipelinesOAuthToken accepting a build id

src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs
Add alias for GetTestRuns method on AzureDevOpsbuild class. Resolves #246
=> (GH-246) Add alias for GetTestRuns method on AzureDevOpsbuild class

src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
Create all test results in GetTestRuns before disposing the TestManagementHttpClient
Resolves #251
=> Create all test results in GetTestRuns before disposing the TestManagementHttpClient

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj, src/Cake.AzureDevOps/Pipelines/ArtifactResourceExtensions.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsArtifactResource.cs
Change type of AzureDevOpsArtifactResource.Type  to AzurePipelinesArtifactType.
Fixes #297
=> (GH-273) Change type of AzureDevOpsArtifactResource.Type  to AzurePipelinesArtifactType

src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetGitClientFactory.cs, src/Cake.AzureDevOps.Tests/Fakes/FakeNullForMethodsGitClientFactory.cs, src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestTests.cs, src/Cake.AzureDevOps.Tests/Repos/PullRequest/CommentThread/AzureDevOpsCommentTests.cs, src/Cake.AzureDevOps/ArgumentChecks.cs, src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs, src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsComment.cs, src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThread.cs
Provides new methods on `AzureDevOpsPullRequest` to delete, update and create comments
Fixes #322
=> (GH-322) Support deleting comments

build.ps1
Stop failing build on warnings since InspectCode currently has a warning:
```
Starting from version 2021.2, InspectCode builds the target solution before starting the analysis to make sure it only finds relevant code issues.
```
=> Ignore warning from InspectCode on AppVeyor

.appveyor.yml
Use Visual Studio 2019 image on AppVeyor as .NET Core 2.1, which is required by some tools used by Cake.Recipe, won't be available on newer images.
=> Use Visual Studio 2019 image on AppVeyor

src/Cake.AzureDevOps/Cake.AzureDevOps.csproj
Add missing dependency for Azure DevOps REST API access
Fixes #353
=> (GH-353) Add missing dependency

src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetBuildClientFactory.cs, src/Cake.AzureDevOps.Tests/Fakes/FakeAllSetWorkItemTrackingClientFactory.cs, src/Cake.AzureDevOps.Tests/Fakes/FakeWorkItemTrackingClientFactory.cs, src/Cake.AzureDevOps.Tests/Pipelines/AzureDevOpsBuildTests.cs, src/Cake.AzureDevOps.Tests/Pipelines/BuildFixture.cs, src/Cake.AzureDevOps/AzureDevOpsAliases.Pipelines.cs, src/Cake.AzureDevOps/AzureDevOpsAliases.WorkItemTracking.cs, src/Cake.AzureDevOps/Boards/WorkItemTracking/AzureDevOpsWorkItem.cs, src/Cake.AzureDevOps/Boards/WorkItemTracking/AzureDevOpsWorkItemSettings.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuild.cs
Returns a list with work item ids associated with the build.
Fixes #356
=> (GH-356) Get work items from build

src/Cake.AzureDevOps/Pipelines/AzureDevOpsArtifactResource.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildArtifact.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildDefinition.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsBuildsSettings.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsChange.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsTestResult.cs, src/Cake.AzureDevOps/Pipelines/AzureDevOpsTimelineRecord.cs, src/Cake.AzureDevOps/Repos/AzureDevOpsCommit.cs, src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestIterationChange.cs, src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestSettings.cs, src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestStatus.cs, src/Cake.AzureDevOps/Repos/PullRequest/BaseAzureDevOpsPullRequestSettings.cs, src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsComment.cs, src/Cake.AzureDevOps/Repos/PullRequest/CommentThread/AzureDevOpsPullRequestCommentThread.cs
Make properties of `AzureDevOpsBuildsSettings`, `AzureDevOpsPullRequestIterationChange`, `AzureDevOpsPullRequestStatus`, `AzureDevOpsComments` and `AzureDevOpsPullRequestCommentThread` only settable during object construction.
=> Make properties init-only

src/Cake.AzureDevOps.Tests/Cake.AzureDevOps.Tests.csproj
Revert update to Moq to > 4.20 due to inclusion of sponsorware that runs during the build.
See https://github.com/moq/moq/issues/1372 for details
This reverts commit 5eba297109f5ff76deecf10cd1491a6b559c17af.
=> Revert "Update dependency Moq to v4.20.0 (#418)"

src/Cake.AzureDevOps.Tests/Cake.AzureDevOps.Tests.csproj, src/Cake.AzureDevOps.Tests/Pipelines/ArtifactResourceExtensionsTests.cs, src/Cake.AzureDevOps/Pipelines/ArtifactResourceExtensions.cs
Makes the comparison for determine artifact types case-insensitive.
Fixes #430
=> Make artifact type comparison case-insensitive

src/Cake.AzureDevOps.Tests/Repos/PullRequest/AzureDevOpsPullRequestSettingsTests.cs, src/Cake.AzureDevOps/AzureDevOpsAliases.PullRequest.cs, src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequestSettings.cs
Don't throw an exception in `AzureDevOpsPullRequestUsingAzurePipelinesOAuthToken` if not running in an Azure Pipelines pull request build if `throwException` is set to `false`.
The parameter `throwExceptionIfPullRequestCouldNotBeFound` has been renamed to `throwException` to make it more obvious that it will also handle exceptions if Azure Pipelines variables are not available. 
Fixes #435
=> (GH-435) Don't throw exception if not running in PR build

.github/renovate.json
`renovate-presets:cake-recipe` (or actually `config:recommended`) includes `:ignoreModulesAndTests` which excludes beside others test folder. By including `:includeNodeModules` it will reset `ignorePaths`.
=> Enable Renovate for test projects

src/Cake.AzureDevOps/Repos/PullRequest/BaseAzureDevOpsPullRequestSettings.cs
Remove obsolete `BaseAzureDevOpsPullRequestSettings.SourceBranch`.
Fixes #456
=> Remove BaseAzureDevOpsPullRequestSettings.SourceBranch

src/Cake.AzureDevOps/Repos/PullRequest/AzureDevOpsPullRequest.cs
Change `AzureDevOpsPullRequest.GetIterationChanges` to return an empty collection instead of `null` in case pull request is not valid.
=> GetIterationChanges should return empty collection instead of null

azure-pipelines.yml
Runs build and unit tests on macOS 13, since macOS 12 image has been deprecated
=> Build on macOS 13
